# Generated by Django 4.1.6 on 2023-04-14 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('helpdesk_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_title', models.CharField(max_length=200)),
                ('ticket_description', models.TextField()),
                ('ticket_status', models.CharField(choices=[('Open', 'Open'), ('Blocked', 'Blocked'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('ticket_time_created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_time_updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_text', models.TextField()),
                ('comment_created_at', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('helpdesk_ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITHelpDesk.ticket')),
            ],
        ),
    ]
